kind: pipeline
name: frontend
steps:
  - name: jsbuild
    image: mhart/alpine-node:6.8.0
    commands:
      - apk add --no-cache make
      - make
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
